### ISSUE TITLE
volume plotting examples (example3 is breaking)

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dmat#34]
![screen shot 2017-04-19 at 1 44 58 pm](https://cloud.githubusercontent.com/assets/18725251/25198983/75e3ce5a-2506-11e7-95b3-633a7628083b.png)

**Comment by fwkoch** [comment]
This was fixed with this commit: https://github.com/3ptscience/steno3dmat/commit/da05905f63f6299aff8a3f5493d703b45923d0ac
